addSbtPlugin("com.geirsson"       % "sbt-ci-release"           % "1.5.7")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"               % "5.6.0")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"              % "0.5.3")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.1.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.7.0")
addSbtPlugin("io.chrisdavenport"  % "sbt-no-publish"           % "0.1.0")